/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import businessLogic.Controller;
import gui.tableModels.ResurseUmaneTM;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import model.Cadru_Didactic;

/**
 *
 * @author S7eve
 */
public class SelectCadruDidacticDialog extends javax.swing.JDialog {
    
    private Controller contr = Controller.getInstance();
    private ResurseUmaneTM tm;
    private boolean selected = false;
    /**
     * Creates new form SelectCadruDidacticDialog
     */
    public SelectCadruDidacticDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        contr.refreshResurseUmaneTM();
        tm = (ResurseUmaneTM) contr.getResurseUmaneTM();
        tableCD.setModel(tm);
        setLocationRelativeTo(null);
    }

    public int getSelectedCDId(){
        if (!selected){
            return -1;
        }
        int index = tableCD.getSelectedRow();
        if (index < 0 ){
            return -1;
        }
        int cdId  = tm.getIdByRow(index);
        return cdId;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCD = new javax.swing.JTable();
        btnSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCD);

        btnSelected.setText("Select");
        btnSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnSelected)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedActionPerformed
        selected=true;
        dispose();
    }//GEN-LAST:event_btnSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelected;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCD;
    // End of variables declaration//GEN-END:variables
}
