/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.director;

import gui.sharedmodels.EchipamenteTM;
import gui.sharedmodels.SaliTM;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import model.Echipament;
import model.ResursaLogistica;
import model.Sala;
import persistence.DirectorRepositoryDB;

/**
 *
 * @author Artiom.Casapu
 */
public class LogisticResourceDialog extends javax.swing.JDialog {

    private boolean ok = false;
    private ResursaLogistica logisticResource;
    
    private final static String SALA = "Sala";
    private final static String ECHIPAMENT = "Echipament";
    
    private List<Sala> sali = new ArrayList<Sala>();
    private List<Echipament> echipamente = new ArrayList<Echipament>();
    
    /**
     * Creates new form LogisticResourceDialog
     */
    public LogisticResourceDialog(JDialog parent,boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        tipResursaComboBox.setModel(new DefaultComboBoxModel(new String[] {  
            SALA,
            ECHIPAMENT
        }));
        
        tipResursaComboBox.setSelectedIndex(0);
        
        List<ResursaLogistica> resurse = DirectorRepositoryDB.getInstance().getAllLogisticResources();
        
        for (ResursaLogistica res : resurse) {
            if (res instanceof Sala) {
                sali.add((Sala)res);
            }
            if (res instanceof Echipament) {
                echipamente.add((Echipament)res);
            }
        }
        
        logisticResourcesTable.setModel(new SaliTM(sali));
    }

    public ResursaLogistica getSelected() {
        return logisticResource;
    }
    
    public boolean isOk() {
        return ok;
    }
    
    private void updateLogisticResource() {
        
        int row = logisticResourcesTable.getSelectedRow();
        
        if (tipResursaComboBox.getSelectedIndex() == 0) {
            logisticResource = sali.get(row);
        } else {
            logisticResource = echipamente.get(row);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salaPanel1 = new javax.swing.JPanel();
        tipResursaComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logisticResourcesTable = new javax.swing.JTable();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        javax.swing.GroupLayout salaPanel1Layout = new javax.swing.GroupLayout(salaPanel1);
        salaPanel1.setLayout(salaPanel1Layout);
        salaPanel1Layout.setHorizontalGroup(
            salaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        salaPanel1Layout.setVerticalGroup(
            salaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tipResursaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipResursaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipResursaComboBoxItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tip");

        logisticResourcesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(logisticResourcesTable);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tipResursaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipResursaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipResursaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipResursaComboBoxItemStateChanged
        
        if (tipResursaComboBox.getSelectedIndex() == 0) {
            logisticResourcesTable.setModel(new SaliTM(sali));
        } else {
            logisticResourcesTable.setModel(new EchipamenteTM(echipamente));
        }
        
    }//GEN-LAST:event_tipResursaComboBoxItemStateChanged

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        ok = true;
        
        updateLogisticResource();
        
        dispose();
        
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable logisticResourcesTable;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel salaPanel1;
    private javax.swing.JComboBox tipResursaComboBox;
    // End of variables declaration//GEN-END:variables
}
