/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.director;

import gui.director.models.CadriDidacticiListModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import model.director.CadruDidactic;
import model.director.ResursaFinanciara;
import model.director.ResursaLogistica;
import model.director.Task;
import model.director.TimeInterval;
import persistence.DirectorRepositoryDB;

/**
 *
 * @author Artiom.Casapu
 */
public class ProjectTask extends javax.swing.JDialog {

    private Task task;
    private boolean ok = false;
    
    private List<ResursaLogistica> logistic = new ArrayList<ResursaLogistica>();
    private List<ResursaFinanciara> financials = new ArrayList<ResursaFinanciara>();
    
    private List<CadruDidactic> echipa = new ArrayList<CadruDidactic>();
    private List<CadruDidactic> cadriDidactici = new ArrayList<CadruDidactic>();
    
    /**
     * Creates new form ProjectTask
     */
    public ProjectTask(JDialog parent,boolean modal,Task t, boolean update) throws SQLException {
        super(parent,modal);
        initComponents();
        
        task = t;
        
        cadriDidactici = DirectorRepositoryDB.getInstance().getCadriDidactici();
        logistic.addAll(t.getResurseLogistice());
        financials.addAll(t.getResurseFinanciare());
        
        if (update) {
            updateComponents();
            echipa.addAll(t.getEchipa());
            cadriDidactici.removeAll(echipa);
        }
        
        echipaList.setModel(new CadriDidacticiListModel(echipa));
        cadriDidacticiList.setModel(new CadriDidacticiListModel(cadriDidactici));
    }
    
    private void updateComponents() {
        denumireTextField.setText(task.getDenumire());
        descriereTextField.setText(task.getDescriere());
        dela.setDate(task.getInterval().getStart());
        panala.setDate(task.getInterval().getEnd()); 
    }
    
    private void updateTask() {
        
        task.setDenumire(denumireTextField.getText());
        task.setDescriere(descriereTextField.getText());
        TimeInterval interval = new TimeInterval();
        interval.setStart((Date)dela.getDate());
        interval.setEnd((Date)panala.getDate());
        task.setInterval(interval);
        task.getEchipa().clear();
        task.getEchipa().addAll(echipa);
        
    }
    
    public boolean isOk() {
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        denumireTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descriereTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        echipaList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        cadriDidacticiList = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        logisticResourcesButton = new javax.swing.JButton();
        financialResourcesButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addToListButton = new javax.swing.JButton();
        removeFromListButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dela = new org.jdesktop.swingx.JXDatePicker();
        panala = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Denumire:");

        jLabel2.setText("Descriere");

        jLabel3.setText("Timp inceput:");

        jLabel4.setText("Timp sfirist:");

        echipaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(echipaList);

        cadriDidacticiList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(cadriDidacticiList);

        jLabel5.setText("Echipa:");

        logisticResourcesButton.setText("Resurse logistice");
        logisticResourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logisticResourcesButtonActionPerformed(evt);
            }
        });

        financialResourcesButton.setText("Resurse financiare");
        financialResourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financialResourcesButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addToListButton.setText("->");
        addToListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToListButtonActionPerformed(evt);
            }
        });

        removeFromListButton.setText("<-");
        removeFromListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromListButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Cadre didactice:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(descriereTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(denumireTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addToListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(removeFromListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(okButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cancelButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(logisticResourcesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(financialResourcesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(denumireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descriereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(panala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addToListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeFromListButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(logisticResourcesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(financialResourcesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToListButtonActionPerformed
        
        int index = cadriDidacticiList.getSelectedIndex();
        
        CadruDidactic cd = cadriDidactici.get(index);
        
        cadriDidactici.remove(cd);
        echipa.add(cd);
        
        echipaList.setModel(new CadriDidacticiListModel(echipa));
        cadriDidacticiList.setModel(new CadriDidacticiListModel(cadriDidactici));
        
    }//GEN-LAST:event_addToListButtonActionPerformed

    private void removeFromListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromListButtonActionPerformed
        
        int index = echipaList.getSelectedIndex();
        
        CadruDidactic cd = echipa.get(index);
        
        echipa.remove(cd);
        cadriDidactici.add(cd);
        
        echipaList.setModel(new CadriDidacticiListModel(echipa));
        cadriDidacticiList.setModel(new CadriDidacticiListModel(cadriDidactici));
        
    }//GEN-LAST:event_removeFromListButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       
        ok = true;
        updateTask();
        dispose();
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void financialResourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financialResourcesButtonActionPerformed
        
        ProjectFinancialResources diag = new ProjectFinancialResources(this,true,task);
        diag.setModal(true);
        diag.setVisible(true);
        
    }//GEN-LAST:event_financialResourcesButtonActionPerformed

    private void logisticResourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logisticResourcesButtonActionPerformed
       
        ProjectLogisticResources diag = new ProjectLogisticResources(this,true,task);
        diag.setModal(true);
        diag.setVisible(true);
        
    }//GEN-LAST:event_logisticResourcesButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToListButton;
    private javax.swing.JList cadriDidacticiList;
    private javax.swing.JButton cancelButton;
    private org.jdesktop.swingx.JXDatePicker dela;
    private javax.swing.JTextField denumireTextField;
    private javax.swing.JTextField descriereTextField;
    private javax.swing.JList echipaList;
    private javax.swing.JButton financialResourcesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logisticResourcesButton;
    private javax.swing.JButton okButton;
    private org.jdesktop.swingx.JXDatePicker panala;
    private javax.swing.JButton removeFromListButton;
    // End of variables declaration//GEN-END:variables
}
