/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administrator.gestionezaresurse;

import businessLogic.AdministratorController;
import gui.administrator.gestionezaresurse.models.ResurseFinanciareTM;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import model.director.ResursaFinanciara;

/**
 *
 * @author S7eve
 */
public class GestioneazaResurseFinanciare extends javax.swing.JDialog {

    private int sumaInBd;
    private AdministratorController contr;
    private ResurseFinanciareTM tableModel;

    /**
     * Creates new form GestioneazaResurseFinanciare
     */
    public GestioneazaResurseFinanciare(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        contr = AdministratorController.getInstance();
        initComboBoxModel();
        refreshTable();
        bindEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableResurseFinanciare = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescriere = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        suma = new javax.swing.JSpinner();
        btnIncaseazaSuma = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSumaTotala = new javax.swing.JTextField();
        cbTip = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtSumaTotalaDupa = new javax.swing.JTextField();
        btnSterge = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableResurseFinanciare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableResurseFinanciare.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableResurseFinanciare);

        jLabel1.setText("Descriere:");

        txtDescriere.setColumns(20);
        txtDescriere.setRows(5);
        jScrollPane2.setViewportView(txtDescriere);

        jLabel2.setText("Suma:");

        suma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sumaStateChanged(evt);
            }
        });

        btnIncaseazaSuma.setText("Incaseaza suma");
        btnIncaseazaSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncaseazaSumaActionPerformed(evt);
            }
        });

        jLabel3.setText("Suma totala in casa:");

        txtSumaTotala.setEditable(false);
        txtSumaTotala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSumaTotalaActionPerformed(evt);
            }
        });

        cbTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Suma totala dupa executarea tranzactiei:");

        txtSumaTotalaDupa.setEditable(false);

        btnSterge.setText("Sterge");
        btnSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeActionPerformed(evt);
            }
        });

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        jLabel5.setText("Tip cheltuiala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSumaTotalaDupa, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSumaTotala, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSterge, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(cbTip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suma)
                                .addComponent(btnIncaseazaSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSumaTotala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSumaTotalaDupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnIncaseazaSuma))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSterge)
                    .addComponent(btnModifica))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncaseazaSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncaseazaSumaActionPerformed
        if (txtDescriere.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Descrierea trebuie completata", "Eroare", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ResursaFinanciara rf = new ResursaFinanciara();
        rf.setDescriere(txtDescriere.getText());
        int sumaInt = (int) suma.getValue();
        rf.setSuma(sumaInt);
        rf.setTip((ResursaFinanciara.TipCheltuiala) cbTip.getSelectedItem());
        try {
            contr.addResursaFinaciara(rf);
        } catch (Exception ex) {
            Logger.getLogger(GestioneazaResurseFinanciare.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Eroare la adaugare " + (sumaInt < 0 ? "cheltuiala" : "suma") + " ", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        refreshTable();
    }//GEN-LAST:event_btnIncaseazaSumaActionPerformed

    private void sumaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sumaStateChanged
        sumaChanged();
    }//GEN-LAST:event_sumaStateChanged

    private void txtSumaTotalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSumaTotalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSumaTotalaActionPerformed

    private void btnStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeActionPerformed

        try {
            final int selectedRow = tableResurseFinanciare.getSelectedRow();
            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(this, "Mai intai selectati o inregistrare", "Eroare", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int result = JOptionPane.showConfirmDialog(this, "Sigur vreti sa efectuati stergerea? ", "?", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.NO_OPTION) {
                return;
            }
            int id = tableModel.getId(selectedRow);
            contr.stergeResursaFinancara(id);
        } catch (Exception ex) {
            Logger.getLogger(GestioneazaResurseFinanciare.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Eroare la stergere", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        refreshTable();
    }//GEN-LAST:event_btnStergeActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        final int selectedRow = tableResurseFinanciare.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Mai intai selectati o inregistrare", "Eroare", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int id = tableModel.getId(selectedRow);
        try {
            contr.modificaResursaFinanciara(id, txtDescriere.getText(), (int) suma.getValue(), (ResursaFinanciara.TipCheltuiala) cbTip.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(GestioneazaResurseFinanciare.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Eroare la modifcare", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        refreshTable();
        tableResurseFinanciare.setRowSelectionInterval(selectedRow, selectedRow);
    }//GEN-LAST:event_btnModificaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncaseazaSuma;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnSterge;
    private javax.swing.JComboBox cbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner suma;
    private javax.swing.JTable tableResurseFinanciare;
    private javax.swing.JTextArea txtDescriere;
    private javax.swing.JTextField txtSumaTotala;
    private javax.swing.JTextField txtSumaTotalaDupa;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        try {
            List<ResursaFinanciara> list = contr.getResurseFinanciare();
            sumaInBd = contr.getSumaResurseFinanciare();

            txtSumaTotala.setText(String.valueOf(sumaInBd));

            Color green = new Color(50, 205, 50);
            Color red = new Color(255, 0, 0);
            Color black = new Color(0, 0, 0);

            if (sumaInBd < 0) {
                txtSumaTotala.setForeground(red);
            } else if (sumaInBd == 0) {
                txtSumaTotala.setForeground(black);
            } else {
                txtSumaTotala.setForeground(green);
            }
            sumaChanged();

            tableModel = new ResurseFinanciareTM(list);
            tableResurseFinanciare.setModel(tableModel);

        } catch (Exception ex) {
            Logger.getLogger(GestioneazaResurseFinanciare.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Eroare la incarcarea resurselor financiale", "Eroare", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    private void initComboBoxModel() {
        cbTip.setModel(new DefaultComboBoxModel(new ResursaFinanciara.TipCheltuiala[]{
            null,
            ResursaFinanciara.TipCheltuiala.CHELTUIALA_CU_MANOPERA,
            ResursaFinanciara.TipCheltuiala.CHELTUIALA_DE_LOGISTICA,
            ResursaFinanciara.TipCheltuiala.CHELTUIELA_CU_MOBILITATE
        }));
    }

    private void bindEvents() {
        ListSelectionModel rowSelectionModel = tableResurseFinanciare.getSelectionModel();
        rowSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        rowSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = tableResurseFinanciare.getSelectedRow();
                if (selectedRow >= 0) {
                    ResurseFinanciareTM model = (ResurseFinanciareTM) tableResurseFinanciare.getModel();
                    txtDescriere.setText((String) model.getValueAt(selectedRow, 0));
                    suma.setValue((int) model.getValueAt(selectedRow, 1));
                    cbTip.setSelectedItem(model.getTip(selectedRow));
                } else {
                    txtDescriere.setText("");
                    suma.setValue(0);
                    cbTip.setSelectedItem(null);
                }
            }
        });
    }

    private void sumaChanged() {
        Color green = new Color(50, 205, 50);
        Color red = new Color(255, 0, 0);
        Color black = new Color(0, 0, 0);

        int sumaNoua = sumaInBd + (int) suma.getValue();
        txtSumaTotalaDupa.setText(String.valueOf(sumaNoua));
        if (sumaNoua < 0) {
            txtSumaTotalaDupa.setForeground(red);
        } else if (sumaNoua == 0) {
            txtSumaTotalaDupa.setForeground(black);
        } else {
            txtSumaTotalaDupa.setForeground(green);
        }

        if ((int) suma.getValue() < 0) {
            btnIncaseazaSuma.setText("Adauga cheltuiala");
        } else {
            btnIncaseazaSuma.setText("Incaseaza suma");
        }
    }
}
